spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: AUTH-APP
          uri: lb://AUTH-APP
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
  application:
    name: GATEWAY
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka